# Allow build scripts to be referenced without being copied into the final image
#FROM scratch AS ctx
#COPY build_files /
#COPY system_files /system_files

# Base Image
FROM quay.io/fedora/fedora-bootc:latest 

# Fedora base image (according to ublue): quay.io/fedora/fedora-bootc:44 

# TODO: /opt?????
### [IM]MUTABLE /opt
## Some bootable images, like Fedora, have /opt symlinked to /var/opt, in order to
## make it mutable/writable for users. However, some packages write files to this directory,
## thus its contents might be wiped out when bootc deploys an image, making it troublesome for
## some packages. Eg, google-chrome, docker-desktop.
##
## Uncomment the following line if one desires to make /opt immutable and be able to be used
## by the package manager.

# RUN rm /opt && mkdir /opt

### MODIFICATIONS
## make modifications desired in your image and install packages by modifying the build.sh script
## the following RUN directive does all the things required to run "build.sh" as recommended.

#RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
#    --mount=type=cache,dst=/var/cache \
#    --mount=type=cache,dst=/var/log \
#    --mount=type=tmpfs,dst=/tmp \
#    /ctx/build.sh 

# Stel de juiste Hostname in voor je NAS
RUN echo "fedora-nas" > /etc/hostname

# 1. Zorg dat shadow-utils geïnstalleerd is
RUN dnf install -y \
    podman \
    shadow-utils \
    sudo \
    && dnf clean all 
    
RUN mkdir -p /var/mnt/storage/nextcloud
# QUADLET-FILES
RUN mkdir -p /etc/containers/systemd
COPY system_files/cockpit.container /etc/containers/systemd/
# TEST NEXTCLOUD HARD INSTALL
COPY system_files/nextcloud.container /etc/containers/systemd/

# 2. Maak de gebruiker aan en stel de wachtwoorden expliciet in
RUN useradd -m -G wheel anna && \
    echo "root:root" | chpasswd --crypt-method SHA512 && \
    echo "anna:anna" | chpasswd --crypt-method SHA512

# 3. Zorg dat SELinux de bestandzichten herstelt voor de shadow-bestanden
RUN restorecon -v /etc/shadow /etc/passwd