# Allow build scripts to be referenced without being copied into the final image
#FROM scratch AS ctx
#COPY build_files /
#COPY system_files /system_files

# Base Image
#FROM quay.io/bootc-devel/fedora-bootc-43-minimal-plus
FROM quay.io/fedora/fedora-bootc:latest

# Fedora base image (according to ublue): quay.io/fedora/fedora-bootc:44 

# TODO: /opt?????
### [IM]MUTABLE /opt
## Some bootable images, like Fedora, have /opt symlinked to /var/opt, in order to
## make it mutable/writable for users. However, some packages write files to this directory,
## thus its contents might be wiped out when bootc deploys an image, making it troublesome for
## some packages. Eg, google-chrome, docker-desktop.
##
## Uncomment the following line if one desires to make /opt immutable and be able to be used
## by the package manager.

# RUN rm /opt && mkdir /opt

### MODIFICATIONS
## make modifications desired in your image and install packages by modifying the build.sh script
## the following RUN directive does all the things required to run "build.sh" as recommended.

#RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
#    --mount=type=cache,dst=/var/cache \
#    --mount=type=cache,dst=/var/log \
#    --mount=type=tmpfs,dst=/tmp \
#    /ctx/build.sh 

RUN dnf install -y \
    podman \
#    shadow-utils \
#    sudo \
    && dnf clean all

### LINTING
## Verify final image and contents are correct.
RUN bootc container lint

# TODO: maak flexibel, haal deze test commando's weg
# --- WACHTWOORDEN EN GEBRUIKERS INSTELLEN ---
# Stel root-wachtwoord in op 'root'
RUN echo "root:root" | chpasswd

# Maak gebruiker 'anna' aan met wachtwoord 'anna' en geef sudo rechten (wheel)
RUN useradd -m -G wheel anna && \
    echo "anna:anna" | chpasswd
